services:
  - type: web
    name: pokemon-arbitrage-ui
    env: node
    buildCommand: cd pokemon-arbitrage-ui && npm install && npm run build
    startCommand: cd pokemon-arbitrage-ui && npm start
    envVars:
      - key: NODE_ENV
        value: production 