services:
  - type: web
    name: pokemon-arbitrage-ui
    env: node
    buildCommand: |
      npm install &&
      pip install -r requirements.txt &&
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/tmp/playwright"
    plan: free
    region: oregon
    autoDeploy: false
    healthCheckPath: / 